### ISSUE TITLE
about the support for the position of vehicles and RSU

### ISSUE THREAD

**Issue by flow233-ai** [coperception/coperception#22]
Hello! My lab is now doing some research about Internet of Vehicles and V2XSim may be very useful for our research.
But my research need the specific positions of every vehicle and RSU and I didn't find this kind of message in the file or codes in the Repo.  
So if specific positions can be incorporated in later versions, it will be very helpful to my research. Thanks a lot!

**Comment by dekunma** [comment]
Hi @flow233-ai, I believe we do have the specific position (if I did not misunderstand your question).
The following code snippet would give the positions of vehicles and RSU:
```python
from nuscenes.nuscenes import NuScenes as V2XSimDataset
v2x_sim = V2XSimDataset(version='v2.0-mini', dataroot='/mnt/d/data/v2x_sim_2.0_mini', verbose=True)
# To investigate a single scene
my_scene = v2x_sim.scene[0]
first_sample_token = my_scene['first_sample_token']
my_sample = v2x_sim.get('sample', first_sample_token)

def get_pose_rec(v2x_sim, channel):
    ref_sd_token = my_sample['data'][channel]
    ref_sd_rec = v2x_sim.get('sample_data', ref_sd_token)
    return v2x_sim.get('ego_pose', ref_sd_rec['ego_pose_token'])

get_pose_rec(v2x_sim, 'LIDAR_TOP_id_0')
# outputs:
#{'token': 'dn3315qva8ka52f5j234j451t840ll96',
# 'timestamp': 6,
# 'rotation': [3.9947416358725856e-07, 0.0, 0.0, 0.9999999999999202],
# 'translation': [-11.506108283996582, 125.10550689697266, 0.1524023413658142]}

get_pose_rec(v2x_sim, 'LIDAR_TOP_id_1')
# outputs:
#{'token': 'i1s306ewwt12du8d5lti46l7mb79jay1',
# 'timestamp': 6,
# 'rotation': [0.6978317588164028, 0.0, -0.0, -0.7162617094241502],
# 'translation': [-3.5915331840515137, 157.4496307373047, 0.0]}
```
V2X-Sim follows the schema of nuScenes. As described in [their documentation](https://github.com/nutonomy/nuscenes-devkit/blob/master/docs/schema_nuscenes.md), `ego_pose` provides the rotation and translation of each vehicle with respect to the global coordinate system.  
Note that being different from the documentation provided by nuScenes, the `z` of `translation` of the RSUs (`id_0`) in our V2X-Sim dataset can have values other than 0 (since the RSUs are not located on the ground level).

**Comment by flow233-ai** [comment]
OK. The `ego_pose` is exactly what I need. Thanks a lot!
