### ISSUE TITLE
Questions for DiscoNet training on V2X-Sim-seg

### ISSUE THREAD

**Issue by zllxot** [coperception/coperception#26]
Hi, when I was trying to train the DiscoNet model on V2X-Sim-seg, I noticed that the forward function in [DiscoNet](https://github.com/coperception/coperception/blob/dd8fbb660300ee763e0bac870f63fc4987440a35/coperception/models/seg/DiscoNet.py) was commented out, which caused the code to automatically jump and execute the forward function in FusionBase. After I uncommented the forward function in DiscoNet, I encountered a new issue:

`AttributeError: 'super' object has no attribute 'build_feat_map_and_feat_list'.`

It seems that there is no code implementation of the build_feat_map_and_feat_list function in FusionBase.

How can I solve this issue? Looking forward to your reply. Thank you!

**Comment by dekunma** [comment]
It is correct that the `forward()` function should be executed in `FusionBase`, because we overrode the `fusion()` method in `DiscoNet`, and it will be called in the last line of `FusionBase`'s `forward()`:
https://github.com/coperception/coperception/blob/dd8fbb660300ee763e0bac870f63fc4987440a35/coperception/models/seg/FusionBase.py#L70
Sorry that I should have removed the commented part to avoid the confusion.

**Comment by zllxot** [comment]
I got it. Thank you for your help!
