### ISSUE TITLE
Some question about tracking dataset

### ISSUE THREAD

**Issue by ellen19967** [coperception/coperception#28]

**Comment by ellen19967** [comment]
Thanks for the great work! I want consult that the parsed dataset for tracking is avaliable? I only find the parsed dataset for detection and segmentation. In addition, How to get object detection results for tracking

**Comment by dekunma** [comment]
We have not provided a parsed dataset for tracking, but it is a good idea to do so. Since I don't have the parsed dataset for tracking at hand, I can help you create and upload one when I'm available this weekend. In the meanwhile, if you would like to create a parsed dataset for tracking from the original V2X-Sim 2.0 dataset on your own, please consult [the documentation for tracking](https://github.com/coperception/coperception/blob/master/tools/track/README.md).  
To get the object detection result for tracking, please run the evaluation program specified in [the documentation for detection](https://github.com/coperception/coperception/blob/master/tools/det/README.md).

**Comment by dekunma** [comment]
Hi @ellen19967, I have uploaded the parsed dataset for tracking to [Google Drive](https://drive.google.com/drive/folders/1zFK9VWvXvYUHatKod5PTl8kZxSFskGGE). Please refer to the README file inside the dataset for usage.

**Comment by ellen19967** [comment]
Thank you so much for your assistance！
