### ISSUE TITLE
Issue with Downloading the complete Dataset

### ISSUE THREAD

**Issue by Maya-ank** [coperception/coperception#29]
@dekunma Thankyou for you kind support in my previous issue. 
I have downloaded the dateset V2X-Sim 1.0, but while preprocessing the data set I also get the same error as #12 . 
Then I checked the size of downloaded LiDAR data and found it to be 15.3 GB, but it should be 16.5 GB. I do not understand why it is not downloading the complete folder. 

<img width="501" alt="error_prepro1" src="https://user-images.githubusercontent.com/91845852/229092565-854fe793-5425-4d51-ad50-a0a9a465a96f.PNG">
<img width="692" alt="error_prepro2" src="https://user-images.githubusercontent.com/91845852/229092608-61f5188a-fa11-428c-8da3-1853db6a9a59.PNG">

So Now as suggested by @dekunma in #12 , I am  thinking of downloading the ' V2X-Sim 2.0 - Parsed datasets & model checkpoints for coperception SDK' . Can you please suggest me how shall i download it directly to my Terminal . As I can not 'gdown' it as it is only shared folder (not a public).

**Comment by dekunma** [comment]
I'm not sure if you were using `gdown` the correct way, since the permission for the datasets is indeed "public," and I am able to download them on my end. For example, for the parsed segmentation dataset:
![image](https://user-images.githubusercontent.com/53892579/229258015-9351ac7e-f432-4fde-9cd2-363a5905d1db.png)
Please try to double check the arguments you passed to `gdown`. If it does not work, we can try to work out what might be the reason.

**Comment by Maya-ank** [comment]
I tried again and it downloaded smoothly. 
Thankyou @dekunma
