### ISSUE TITLE
Change the Perception Range

### ISSUE THREAD

**Issue by lianggroup** [coperception/coperception#30]
Thanks for your solid work on collaborative perception!
I have a question about the perception range. Is there a way to modify the perceived range （default [-32,32]）？
But if it is impossible to modify it, it doesn't matter.
I am looking forward to your answer.  Thanks a lot!

**Comment by dekunma** [comment]
Hi @lianggroup, to change the perceived range, please change `voxel_size` and `area_extents` in `Config.py`:
https://github.com/coperception/coperception/blob/f8fa120b579643d141c4a5d0e8cd2b0b7ec7c913/coperception/configs/Config.py#L73-L82
When changing the range, please make sure to change the `voxel_size` accordingly so that the generated BEV-based pseudo-image has a length and width of 256 (e.g. (32 + 32) / 0.25 = 256).
The lines commented out showed the config of a perceived range of `[-48, 48]`).

**Comment by lianggroup** [comment]
OK. I see. Thanks again for your answer. This answer helped me a lot.
