### ISSUE TITLE
error in : make train_disco

### ISSUE THREAD

**Issue by Maya-ank** [coperception/coperception#31]
Thankyou for your great work and kind help in my previous issues. I have encountered one more error and would like some help. 
I have trained upperbound and it trained well. Now I am trying to train disconet and getting the error like this :

<img width="701" alt="error1" src="https://user-images.githubusercontent.com/91845852/231757345-1d0e8114-46cd-4d21-87e7-9028dba66808.PNG">

![image](https://user-images.githubusercontent.com/91845852/231757279-790b485e-a1fd-4935-939b-1308d88b97fa.png)

**Comment by dekunma** [comment]
Could you print the shapes of the tensors in `feature_list` so that I can take a look?

**Comment by Maya-ank** [comment]
Yes sure, here it is: 

<img width="196" alt="tensor-print" src="https://user-images.githubusercontent.com/91845852/231986415-6157566a-c119-4615-8e44-9dd9a4a60c27.PNG">

**Comment by dekunma** [comment]
It looks like the first dimension of input BEV data is only 12 instead of 24. This might be the reason why you are having a 0 in the first dimension of the last three agents. 
Did you modify the original code? We have not encountered a similar problem before, and I am not able to reproduce it:
![image](https://user-images.githubusercontent.com/53892579/232355119-c7b14bf7-9a6b-4b31-82ca-e21b95d4e72b.png)

I would recommend trying to trace the upper stream of `feature_list` to see why the first dimension was halved. For example, the shape of `feat_maps` passed to `build_feature_list` function should be `[24, 256, 32, 32]`.

The shape of `bev` passed to DiscoNet should be `[24, 1, 13, 256, 256]`.

**Comment by Maya-ank** [comment]
Thankyou for your kind support.
I made a mistake as the issue occurred due to the interaction between DataParallel and the build_feature_list function when using multiple GPUs ( I used 2 GPUs) . The function was not adapted to handle the change in batch size, which resulted in the incorrect distribution of feature maps among agents and caused the concatenation error.

**Comment by JunjH** [comment]
> Thankyou for your kind support. I made a mistake as the issue occurred due to the interaction between DataParallel and the build_feature_list function when using multiple GPUs ( I used 2 GPUs) . The function was not adapted to handle the change in batch size, which resulted in the incorrect distribution of feature maps among agents and caused the concatenation error.

I have encountered the same issue and would like to ask how to fix it in order to enable training with multiple GPUs.

**Comment by Maya-ank** [comment]
I think there is some confusion with my explanation. 
I was initially trying with 2 GPUs by mistake which was causing the error, but later on I switched to 1 GPU and it got fixed.

**Comment by Xu2729** [comment]
> > Thankyou for your kind support. I made a mistake as the issue occurred due to the interaction between DataParallel and the build_feature_list function when using multiple GPUs ( I used 2 GPUs) . The function was not adapted to handle the change in batch size, which resulted in the incorrect distribution of feature maps among agents and caused the concatenation error.
> 
> I have encountered the same issue and would like to ask how to fix it in order to enable training with multiple GPUs.

I have also encountered this issue. I think this is caused by passing the wrong `batch_size` to the model in the `forward` function. My fix is as follows:

In `coperception/utils/CoDetModule.py`, try to find all `batch_size`, replace it with `batch_size // torch.cuda.device_count()` (and also make sure `batch_size % torch.cuda.device_count() == 0`). Take `step` function as examlpe:

```python
    def step(self, data, batch_size, num_agent):

        bev_seq = data["bev_seq"]
        labels = data["labels"]
        reg_targets = data["reg_targets"]
        reg_loss_mask = data["reg_loss_mask"]
        anchors = data["anchors"]
        trans_matrices = data["trans_matrices"]
        num_all_agents = data["num_agent"]

        batch_size_per_gpu = batch_size // torch.cuda.device_count() # get batch_size for per GPU
        # with torch.autograd.set_detect_anomaly(True):
        if self.config.flag.startswith("when2com") or self.config.flag.startswith(
            "who2com"
        ):
            if self.config.split == "train":
                result = self.model(
                    bev_seq,
                    trans_matrices,
                    num_all_agents,
                    batch_size=batch_size_per_gpu, # replace batch_size with batch_size_per_gpu 
                    training=True,
                )
            else:
                result = self.model(
                    bev_seq,
                    trans_matrices,
                    num_all_agents,
                    batch_size=batch_size_per_gpu, # replace batch_size with batch_size_per_gpu 
                    inference=self.config.inference,
                    training=False,
                )
        ...
```
