### ISSUE TITLE
DiscoNet test result : Error in IoU 0.5 & 0.7 reults

### ISSUE THREAD

**Issue by Maya-ank** [coperception/coperception#36]
I would like to thankyou for your great work & consistent support.
I have raised some concerns before in #33 and got a quick fix by @dekunma, which I am very thankful of. 
I have noticed that the mAP values for each agent at IoU thresholds of 0.5 and 0.7 are exactly the same, which is unusual. 

Also, please correct me if I am wrong, the average local mAP of all 5 Agents is somewhat different than what I calculated normally. 

average mAP@0.5 = (0.6579220294952393 + 0.7744371891021729 + 0.7319439053535461 + 0.7088317275047302 + 0.7414842844009399) / 5
= 0.7229238271903257 

This the test result which I am referring to:
![image](https://github.com/coperception/coperception/assets/91845852/6002e097-e8dc-4bb3-9e19-81fb96a10ad3)

Please have a look. 
Thank you

**Comment by dekunma** [comment]
Thank you for pointing this out. It was a silly typo that resulted in each agent having the same mAPs at 0.5 and 0.7. I never noticed this since we only focused on the average local mAP of all agents.

For the average mAPs, you are right that they are not the arithmetic average of the mAPs of all the agents, because the average mAPs were calculated collectively based on the detection results from all agents, instead of individually.
