### ISSUE TITLE
issue to train the tracker

### ISSUE THREAD

**Issue by huiyegit** [coperception/coperception#40]
Thank you for your great work. I would like to train the tracker via the command '**make sort**'.  The error shows that one file can not be found. How can I find this file?

<img width="891" alt="Screen Shot 2023-09-14 at 9 14 31 PM" src="https://github.com/coperception/coperception/assets/31486250/cdb6aee1-d06b-4781-b17d-b2588f8d2674">

**Comment by dekunma** [comment]
The trackers are evaluated using the results obtained from the inference stage of detection tasks. (As per the first sentence of [Tracking Documentations](https://coperception.readthedocs.io/en/latest/tools/track/)).
In your case, make sure that you have executed the evaluation (test) program for DiscoNet without RSU, so that the corresponding file needed for tracking could be generated.
If the same error persists, please let me know.

**Comment by huiyegit** [comment]
Yes, the tracking task needs the evaluation results of detection task. I can run the ''**make sort**" command and get the results. Thank you.
