### ISSUE TITLE
Camera Only Coperception

### ISSUE THREAD

**Issue by scdrand23** [coperception/coperception#48]
Hi,

Thanks for the amazing work and for creating this library.
I have two questions.
     1) I have a similar dataset collected in the v2x setup, how can I use this package? (A high-level guide would be great)
     2) Does the library support running camera-only input coperception?

Thanks,

**Comment by dekunma** [comment]
Hi @scdrand23 ,

> 1) I have a similar dataset collected in the v2x setup, how can I use this package? (A high-level guide would be great)

I personally think that our package is not designed in the most extensible way, since it only supports datasets structured the same way as [nuScenes](https://www.nuscenes.org/). If your dataset can also be structured the same way, then I believe you can first look into `coperception/datasets` to create your own PyTorch dataset class; then look into `tools/det/create_data_det.py` to see how to preprocess your dataset for the training and evaluation pipeline. (And `tools/seg` and `tools/track`) for the other two tasks.  
Please also be mindful that the difficulty of making your dataset work on our library might vary largely depending on how similar your dataset is to our [V2X-Sim dataset](https://ai4ce.github.io/V2X-Sim/).

> 2) Does the library support running camera-only input coperception?

Our library currently doesn't support camera-only input coperception.

**Comment by scdrand23** [comment]
Thank you for the quick response and detailed answers.
